arch:
    max_epochs: 3
    validate_first: True
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (384, 384)
    train:
        batch_size: 4
        dataset: ['Image']
        path: ["/workspaces/packnet-sfm/datasets/model_of_mouth/WIN_20240325_18_01_15_Pro.mp4/"]
        split: ["{:08d}"]
        # depth_type: ['velodyne']
        # repeat: [100]
    validation:
        dataset: ['Image']
        path: ['/workspaces/packnet-sfm/datasets/model_of_mouth/WIN_20240326_14_35_09_Pro.mp4/']
        split: ["{:08d}"]
        # depth_type: ['velodyne']
    test:
        dataset: ['Image']
        path: ['/workspaces/packnet-sfm/datasets/model_of_mouth/WIN_20240326_14_35_09_Pro.mp4/']
        split: ["{:08d}"]
        # depth_type: ['velodyne']
save:
    folder: '/workspaces/packnet-sfm/runs/train/'
    # pretrained: '/workspaces/packnet-sfm/runs/train/default_config-train_PxCam-2024.03.26-09h30m39s/epoch=49_-loss=0.000.ckpt'
    depth:
        rgb: True
        # viz: True
        # npz: True
        png: True
checkpoint:
    filepath: '/workspaces/packnet-sfm/runs/train/'
    save_top_k: -1